#!/usr/bin/env python3
"""1% CLUB — Module 4 report + project closing note. NO NEW RUNS.

Everything is read from the stored Module 3 / Module 4 artefacts. Nothing is
re-simulated. Writes:
    reports/club1pct_module4_gear_trail.txt
    reports/club1pct_PARKED.txt
"""
from __future__ import annotations

from pathlib import Path

import pandas as pd

TRACK = Path(__file__).resolve().parents[1]
M3, M4 = TRACK / "data" / "m3", TRACK / "data" / "m4"
R4 = TRACK / "reports" / "club1pct_module4_gear_trail.txt"
RP = TRACK / "reports" / "club1pct_PARKED.txt"
TRACE = ["BLUESTARCO", "TVSMOTOR", "CUMMINSIND", "DIXON", "CDSL"]
ORDER = ["CONTROL", "SCALE-10x", "SCALE-20x"]
EW = {"cagr": 18.70, "max_dd": -35.50}

L = []
def A(s=""): L.append(s)


def main():
    S = pd.read_parquet(M4 / "module4_summary.parquet").set_index("variant").loc[ORDER].reset_index()
    ladder = pd.read_parquet(M3 / "module3_ladder.parquet")

    A("=" * 78)
    A("1% CLUB 52-WEEK-HIGH BREAKOUT — MODULE 4: BRAHMASTRA GEAR TRAIL")
    A("=" * 78)
    A()
    A("  Pre-registered. Declared in advance to be the LAST run against this")
    A("  window. Generated from the stored ledgers by")
    A("  scripts/club1pct_module4_report.py — nothing was re-simulated.")
    A("  Engine: scripts/module4_brahmastra.py")
    A()
    A("  VERDICT: FAIL for CONTROL and BOTH scales, on the max-drawdown gate.")
    A("  Nothing here validates any configuration.")
    A()
    A("  >>> CORRECTION STAMP, added after an adversarial audit <<<")
    A("  The gate-5 'beats random-entry null' rows below record what the ORIGINAL")
    A("  run produced and are preserved as the historical record. They are WRONG.")
    A("  The null was a broken instrument: it charged the flat Rs 15.93 DP sell")
    A("  fee against a one-share notional, handicapping it by 0.7053 R per trade.")
    A("  With the null fixed (scripts/club1pct_null_fix.py), gate 5 is FAIL for")
    A("  CONTROL (p 0.484), SCALE-10x (p 0.822) and SCALE-20x (p 0.658).")
    A("  Corrected figures: data/m2/null_corrected.parquet. This makes the")
    A("  verdicts WORSE, never better. See reports/club1pct_PARKED.txt.")
    A()
    A("-" * 78)
    A("WHAT WAS REGISTERED")
    A("-" * 78)
    A("  BASE = Module 2 config A, unchanged: same entry (F1..F5 + breakout),")
    A("  portfolio, slots, tie-break, costs, slippage, exit-at-next-open, no")
    A("  rebalancing. The EMA220 leg and the -15% stop leg both stay ACTIVE.")
    A()
    A("  GEAR TRAIL, added on top; may only ever exit EARLIER than the base.")
    A("    peak           = highest CLOSE since entry")
    A("    max_profit_pct = peak / entry_fill - 1")
    A("    gear 1  max_profit < G2 trigger     -> no trail, base rules only")
    A("    gear 2  max_profit >= G2 trigger    -> exit if close <= peak*(1-G2 trail)")
    A("    gear 3  max_profit >= G3 trigger    -> exit if close <= peak*(1-G3 trail)")
    A("    Gear 3 supersedes gear 2; gears never step back down.")
    A("    Evaluated on the CLOSE, executed at the NEXT session's OPEN.")
    A()
    A("  RESCALE, declared before the run, original shape held exactly")
    A("    shape: G2 trail = 0.6 x G2 trigger; G3 trail = 0.089 x G3 trigger;")
    A("           G3 trigger = 1.8 x G2 trigger")
    A("    10x : G2 +25% / trail 15%   G3 +45% / trail 4%")
    A("    20x : G2 +50% / trail 30%   G3 +90% / trail 8%")
    A("    No third scale. No interpolation. No searching around a winner.")
    A()
    A("  DECLARED ATTRIBUTION: when a base leg and a gear fire on the same")
    A("  close, the exit is attributed to the BASE leg. A gear count therefore")
    A("  means 'the gear exited EARLIER than the base would have'.")
    A()
    A("  DECLARED LIMITS, written before the run")
    A("    1. The original gears are 15-minute intraday FUTURES parameters. At a")
    A("       133-session median hold they are meaningless unrescaled. The")
    A("       rescale above was declared, not chosen after seeing results.")
    A("    2. The original exits INTRABAR. This panel is daily-close only, so")
    A("       this is a WEAKENED version of the mechanism. A NEGATIVE RESULT")
    A("       HERE DOES NOT MEAN THE ORIGINAL DOES NOT WORK.")
    A()
    A("  DECLARED READING RULE: both scales moving the same direction versus")
    A("  control = evidence the mechanism is real. One scale winning while the")
    A("  other fails = NOISE, and must be reported as noise.")
    A()
    A("-" * 78)
    A("CONTROL CORRECTNESS CHECK")
    A("-" * 78)
    A("  Plain config A with no trail vs data/m2/module2_trades_A.parquet:")
    A("    rows 125 vs 125    ledger equals: True")
    A("    equity curve identical: True, max abs diff 0.000000")
    A("    (max_gear / max_profit_pct are ADDITIONS; compared on 17 shared cols)")
    A()

    for _, r in S.iterrows():
        A("=" * 78)
        A(f"{r['variant']}")
        A("=" * 78)
        g = [("net expectancy > 0 after costs", r["exp_rs"] > 0, f"Rs {r['exp_rs']:,.0f}/trade"),
             ("profit factor >= 1.3", r["pf"] >= 1.3, f"{r['pf']:.3f}"),
             ("max drawdown <= 15%", r["max_dd"] >= -15.0, f"{r['max_dd']:.2f}%"),
             ("trades >= 60", r["trades"] >= 60, f"{int(r['trades'])}"),
             ("beats random-entry null, p < 0.05", r["p"] < 0.05, f"p = {r['p']:.4f}")]
        A("1. GATES")
        for nm, ok, v in g:
            A(f"     [{'PASS' if ok else 'FAIL'}]  {nm:<36} {v}")
        A(f"     OVERALL: {'PASS' if all(x[1] for x in g) else 'FAIL'}")
        A("2. HEADLINE")
        A(f"     closed trades {int(r['trades'])}    win rate {r['win_rate']:.2f}%")
        A(f"     expectancy    Rs {r['exp_rs']:,.0f} = {r['exp_r']:+.3f} R")
        A(f"     profit factor {r['pf']:.3f}     CAGR {r['cagr']:.2f}%")
        A(f"     max drawdown  {r['max_dd']:.2f}%   longest {int(r['longest_dd'])} days")
        A(f"     final equity  Rs {r['final_equity']:,.0f}")
        A("3. HOLDING PERIOD (sessions)")
        A(f"     median {r['hold_med']:.0f}   IQR {r['hold_q1']:.0f}..{r['hold_q3']:.0f}")
        A("4. EXIT REASON SPLIT")
        for lbl, k in (("EMA220 leg", "ex_ema"), ("-15% stop", "ex_stop"),
                       ("Gear 2 trail", "ex_g2"), ("Gear 3 trail", "ex_g3"),
                       ("open at end", "ex_open")):
            A(f"     {lbl:<14} {int(r[k]):>4}   ({100*r[k]/r['total']:5.1f}%)")
        A("5. TOTAL COSTS PAID")
        A(f"     Rs {r['costs']:,.0f}   = {r['cost_pct']:.2f}% of final equity")
        A("6. GEAR REACH")
        A(f"     ever reached gear 2: {int(r['reached_g2'])} / {int(r['total'])}"
          f"   ({100*r['reached_g2']/r['total']:.1f}%)")
        A(f"     ever reached gear 3: {int(r['reached_g3'])} / {int(r['total'])}"
          f"   ({100*r['reached_g3']/r['total']:.1f}%)")
        if r["variant"] != "CONTROL":
            A("     The rescale did NOT make the mechanism inert — the gears fire")
            A(f"     {int(r['ex_g2']+r['ex_g3'])} real exits here. This is a result, not a dead parameter.")
        A()

    A("=" * 78)
    A("7. THE FIVE TRADES THAT CARRY CONFIG A")
    A("=" * 78)
    A("  CAVEAT: trade paths DIVERGE between variants. Because exits change,")
    A("  slots and cash free at different times, so different signals get")
    A("  filled. This is a portfolio-path comparison, not a controlled")
    A("  per-trade one.")
    for sym in TRACE:
        A(f"\n  {sym}")
        for n in ORDER:
            T = pd.read_parquet(M4 / f"module4_trades_{n}.parquet")
            sub = T[T["symbol"] == sym]
            if not len(sub):
                A(f"    {n:<10} — no trade taken")
                continue
            for _, t in sub.iterrows():
                A(f"    {n:<10} {t['entry_date'].date()} -> {t['exit_date'].date()}  "
                  f"{t['exit_reason']:<12} {t['ret_pct']:+8.1f}%  Rs {t['pnl']:>10,.0f}  "
                  f"[peak +{t['max_profit_pct']:.0f}%, gear {int(t['max_gear'])}]")
    A()
    A("  Totals across ALL trades in these five symbols:")
    for n in ORDER:
        T = pd.read_parquet(M4 / f"module4_trades_{n}.parquet")
        s = T[T["symbol"].isin(TRACE)]
        fe = float(S[S["variant"] == n]["final_equity"].iloc[0])
        A(f"    {n:<10} Rs {s['pnl'].sum():>10,.0f} across {len(s)} trades"
          f"   = {100*s['pnl'].sum()/(fe-1_000_000):.1f}% of net profit")
    A()
    A("  At 10x the gears AMPUTATED all five. DIXON is the clearest: a +341% /")
    A("  Rs 407k winner cut at +49.3% / Rs 70k, exited 2020-07-28, under two")
    A("  months in, at a peak of only +54%. Once a trade clears +45%, a 4% trail")
    A("  off the peak cannot survive normal volatility in a stock that went on")
    A("  to run 477% above entry.")
    A("  At 20x it splits: CUMMINSIND (+215.2% vs +188.6%) and CDSL (+214.5% vs")
    A("  +216.1%) came out level or better, because an 8% trail exits nearer the")
    A("  top than the EMA220 does. DIXON was still amputated.")
    A()
    A("=" * 78)
    A("8. SHAPE RULE")
    A("=" * 78)
    ctrl = S[S["variant"] == "CONTROL"].iloc[0]
    for col, lbl in (("exp_r", "expectancy R"), ("cagr", "CAGR"),
                     ("pf", "profit factor"), ("max_dd", "max drawdown")):
        d10 = S[S["variant"] == "SCALE-10x"].iloc[0][col] - ctrl[col]
        d20 = S[S["variant"] == "SCALE-20x"].iloc[0][col] - ctrl[col]
        same = (d10 > 0 and d20 > 0) or (d10 < 0 and d20 < 0)
        A(f"  {lbl:<16} vs control:  10x {d10:+.3f}   20x {d20:+.3f}   "
          f"-> {'SAME DIRECTION' if same else 'OPPOSITE == NOISE'}")
    A()
    A("  The RETURN effect is real: both scales move the same way, and it is")
    A("  consistently NEGATIVE. The DRAWDOWN effect is NOISE and is reported as")
    A("  noise — one scale improves it by a point, the other worsens it by a")
    A("  point. That column has now failed to show direction in two consecutive")
    A("  modules.")
    A()
    A("=" * 78)
    A("9. BENCHMARK")
    A("=" * 78)
    A(f"  Universe EW buy & hold, no rebalancing: CAGR {EW['cagr']:.2f}%  "
      f"maxDD {EW['max_dd']:.2f}%")
    beat = S[S["cagr"] > EW["cagr"]]["variant"].tolist()
    A(f"  Variants beating it on CAGR: {beat if beat else 'NONE'}")
    A("  The gear trail has not earned its complexity, and it moves AWAY from")
    A("  the bar rather than toward it.")
    A()
    A("=" * 78)
    A("10. IS A PROFIT-CONDITIONAL TRAIL DIFFERENT FROM EXIT SPEED?")
    A("=" * 78)
    A("  It is different, and it is WORSE. Every variant from Modules 3 and 4,")
    A("  sorted by median holding period:")
    A()
    m3 = ladder[["N", "hold_med", "cagr", "exp_r", "max_dd", "trades"]].copy()
    m3["variant"] = "M3 EMA" + m3["N"].astype(str)
    m3 = m3.drop(columns="N")
    both = pd.concat([m3, S[["variant", "hold_med", "cagr", "exp_r", "max_dd", "trades"]]])
    both = both.sort_values("hold_med")
    for ln in both.round(2).to_string(index=False).splitlines():
        A("    " + ln)
    A()
    A("  If the gear trail were unconditional exit speed under another name it")
    A("  would sit on the same hold-length curve. It does not. SCALE-10x holds")
    A("  LONGER than EMA150 (94 vs 85 sessions) and returns substantially LESS")
    A("  (12.28% vs 15.56% CAGR; 0.48R vs 0.73R). SCALE-20x is off the curve the")
    A("  same way.")
    A()
    A("  Mechanism: an unconditional moving average cuts indiscriminately, so it")
    A("  still lets some large winners run. A profit-conditional trail activates")
    A("  ONLY on trades that are winning, and tightens MOST on the ones winning")
    A("  biggest. In a book where five trades carry half the profit, a rule that")
    A("  targets the top of the winner distribution is strictly more damaging")
    A("  than one that cuts at random. Not the same effect renamed — the same")
    A("  effect plus an adverse-selection penalty.")
    A()
    A("=" * 78)
    A("SURPRISES")
    A("=" * 78)
    A("  * SCALE-10x has the BEST win rate in the whole project (47.47%) and")
    A("    nearly the worst CAGR. The trail converts large winners into modest")
    A("    ones, flattering the hit rate while destroying the payoff")
    A("    distribution. Anyone screening on win rate picks the worst config.")
    A("  * Costs rose 61% at 10x (Rs 93,770 -> Rs 151,381) on a SMALLER final")
    A("    equity: drag went 1.69% -> 3.94%.")
    A("  * 20x beat control on two of the five carriers. That is the only sign")
    A("    anywhere in this run that a tight trail off the peak can improve on")
    A("    an EMA exit. It did not survive aggregation, but it is recorded as")
    A("    honest counter-evidence.")
    A()
    A("=" * 78)
    A("ARTEFACTS")
    A("=" * 78)
    for n in ORDER:
        A(f"  data/m4/module4_trades_{n}.parquet")
        A(f"  data/m4/module4_equity_{n}.parquet")
    A("  data/m4/module4_summary.parquet")
    A()
    A("  Project closing note: reports/club1pct_PARKED.txt")
    A()
    R4.write_text("\n".join(L) + "\n")
    print(f"written: {R4}  ({len(L)} lines)")

    # ---------------- closing note
    P = []
    def B(s=""): P.append(s)
    B("=" * 78)
    B("1% CLUB 52-WEEK-HIGH BREAKOUT — PROJECT CLOSED, STRATEGY PARKED")
    B("=" * 78)
    B()
    B("  Parked 2026-08-16. This window is BURNT for this spec.")
    B()
    B("-" * 78)
    B("WHAT HAPPENED")
    B("-" * 78)
    B("  Modules 2, 3 and 4 all FAIL as registered. Every configuration tested")
    B("  breached the max-drawdown gate; Module 2 config B and Module 3 N=20")
    B("  also failed on other gates.")
    B()
    B("  FOUR INDEPENDENT TESTS REACHED THE SAME CONCLUSION:")
    B("    1. the random-entry null")
    B("    2. the equal-weight universe benchmark")
    B("    3. the exit ladder (Module 3)")
    B("    4. the gear trail (Module 4)")
    B("  None of them found an entry edge worth the complexity.")
    B()
    B("-" * 78)
    B("WHAT WAS ACTUALLY LEARNED")
    B("-" * 78)
    B("  * THE ENTRY RULES HAVE NO MEASURABLE EDGE.")
    B("    An earlier draft of this note claimed the entry added a constant")
    B("    0.54-0.74 R over a same-holding-period random entry. THAT CLAIM WAS")
    B("    AN ARTEFACT of a broken null and is WITHDRAWN. Against the corrected")
    B("    null, 7 of the 9 variants run have NEGATIVE edge. The headline")
    B("    configuration (M2 config A) sits 0.2834 R BELOW the null mean.")
    B("    The two positive readings — config B +0.1025 R and M3 EMA150")
    B("    +0.0414 R — carry p = 0.204 and p = 0.254, i.e. noise.")
    B("    Almost all the variation in headline results is HOLDING PERIOD.")
    B()
    B("  * Exit speed IS a real lever, and it points toward SLOWER. Return rose")
    B("    monotonically across EMA 20 -> 50 -> 150 -> 220 with no inflection.")
    B("    N=220 is the best rung and nothing rewards moving off it.")
    B()
    B("  * A PROFIT-CONDITIONAL trail is WORSE than unconditional exit speed at")
    B("    the same holding period, because it selectively targets the largest")
    B("    winners. SCALE-10x held longer than EMA150 and returned less.")
    B()
    B("  * Portfolio drawdown was NOT controllable by any exit rule tested. The")
    B("    drawdown column showed no direction in either Module 3 or Module 4.")
    B("    It is a market event, not an exit-rule variable.")
    B()
    B("-" * 78)
    B("ADVERSARIAL AUDIT — EVERY DEFECT FOUND WAS FLATTERING")
    B("-" * 78)
    B("  A 360-degree correctness audit was run over Modules 2/3/4 AFTER the")
    B("  park (scripts/club1pct_audit.py). It attacked flattering and damaging")
    B("  errors with equal effort. It found EIGHT defects. EVERY ONE of them")
    B("  pointed the same way — flattering. NONE pointed the other way.")
    B()
    B("  1. VERDICT-DECIDING. The random-entry null passed a ONE-SHARE price as")
    B("     the trade notional, so the flat Rs 15.93 DP sell fee was charged")
    B("     against a ~Rs 493 median notional while the strategy paid it on a")
    B("     ~Rs 1.47 lakh position — a 1,096x handicap, 0.7053 R per trade.")
    B("     FIXED and re-measured. Consequence below.")
    B("  2. The null drew from `ema220 finite`, true from a symbol's first bar,")
    B("     so 12.0% of the pool (56,212 of 468,598 cells) was pre-warmup and")
    B("     untradeable. FIXED: it now draws from the strategy's `eligible` flag.")
    B("  3. The null excludes actual signal days, making it a 'random NON-signal")
    B("     entry'. LEFT IN PLACE by design, but MEASURED: the tilt is at most")
    B("     0.098 R and mostly noise-level. It was NOT materially distorting the")
    B("     comparison.")
    B("  4. Position budget basis is post-exit cash + survivors marked at the")
    B("     prior close, which is not equity[d-1]; one trade of 125 breached the")
    B("     10% cap, at 10.0149%. Immaterial (0.015pp).")
    B("  5. Final equity marks open positions with no exit costs, while the")
    B("     ledger books Rs 5,633 of hypothetical sell costs. CAGR flattered by")
    B("     about 0.10%.")
    B("  6. The p-value is ONE-SIDED. This was never stated in any report until")
    B("     now. It is stated here: p = fraction of null iterations whose mean")
    B("     equals or exceeds the strategy's expectancy. One-sided.")
    B("  7. Module 3 recomputed EMA on the pivoted matrix, which differs for the")
    B("     five symbols with data gaps (max 0.96% relative, PATANJALI). No")
    B("     effect at N=220. Previously reported.")
    B("  8. `shares <= 0` was counted as a 'cash skip' when it actually means the")
    B("     share price exceeds 10% of equity. Mislabels skip counts only.")
    B()
    B("  WHAT PASSED, verified rather than assumed: no look-ahead at any use")
    B("  site (252-max exclusive of today, entries at the NEXT open, exits")
    B("  decided on the signal close, ranking from signal-day data); cash + market")
    B("  value reconstructed independently from the ledger matches the stored")
    B("  equity curve to Rs 0.000000 across all 2,879 sessions; the ledger")
    B("  reconciles to final equity with residual -Rs 0.00; costs charged and")
    B("  independently recomputed on BOTH sides of every trade; slippage adverse")
    B("  on both sides; no trade on a missing session; no overlapping positions;")
    B("  cash never negative.")
    B()
    B("-" * 78)
    B("THE CORRECTED NULL — GATE 5 IS 'FAIL' FOR ALL NINE VARIANTS")
    B("-" * 78)
    B("  Re-measured with defects 1 and 2 fixed, 500 iterations, seed 20260816,")
    B("  null trade sized at Rs 1,00,000 = 10% of starting capital (the low end")
    B("  of the strategy's actual Rs 1.47 lakh median, so still conservative).")
    B("  No config was re-run; only the measuring instrument was repaired.")
    B()
    for _, r in pd.read_parquet(TRACK / "data" / "m2" / "null_corrected.parquet").iterrows():
        B(f"    {r['variant']:<13} exp {r['exp_r']:+.4f} R   old null {r['old_null_mean']:+.4f} "
          f"-> new {r['new_null_mean']:+.4f}   old p {r['old_p']:.3f} -> new p {r['new_p']:.3f}"
          f"   {r['old_gate5']} -> {r['new_gate5']}")
    B()
    B("  ALL NINE flip from PASS to FAIL. This makes every verdict in this")
    B("  project WORSE, never better. The park is more strongly supported than")
    B("  when it was declared.")
    B()
    B("-" * 78)
    B("SURVIVORSHIP, MEASURED")
    B("-" * 78)
    B("  58 of the 188 symbols did not exist on 2015-01-01. Config A took 23 of")
    B("  its 125 trades (18.4%) in those names, and those 23 trades produced")
    B("  Rs 20,87,994 of Rs 45,33,056 — 46.1% OF TOTAL P&L. Nearly half the")
    B("  profit comes from names that had not listed when the window opened, and")
    B("  each is in the universe only because of what it became by 2026.")
    B("  (The F&O-membership question proper CANNOT be verified — no historical")
    B("  NSE F&O constituent list is held locally. 58/188 is the listing-based")
    B("  LOWER bound on the bias.)")
    B()
    B("-" * 78)
    B("THE DRAWDOWN, DECOMPOSED")
    B("-" * 78)
    B("  Config A peak 2020-02-19 Rs 15,96,180 -> trough 2020-05-27 Rs 11,91,354,")
    B("  -Rs 4,04,826 = -25.36%. Of that, only Rs 24,243 (6.0%) was realised")
    B("  losses on 10 closed trades; Rs 3,80,584 (94.0%) was change in unrealised")
    B("  marks on open positions.")
    B()
    B("    date          config A dd    NIFTY dd")
    B("    2020-02-19        0.00%       -1.91%   (peak)")
    B("    2020-03-23      -22.94%      -38.44%   (NIFTY bottom)")
    B("    2020-05-27      -25.36%      -24.65%   (config A trough)")
    B()
    B("  Read it honestly, both halves. Through the crash itself the book fell")
    B("  22.9% against the index's 38.4% — it materially OUTPERFORMED, and the")
    B("  damage was overwhelmingly marks on positions it was holding, not")
    B("  decisions it made. But its trough came TWO MONTHS AFTER the index's:")
    B("  between 2020-03-23 and 2020-05-27 NIFTY rose about 22% while the")
    B("  strategy fell a further 3%. Nine positions exited on the EMA220 leg")
    B("  between 11 and 24 March — at the bottom — and the book re-entered in")
    B("  April into HINDUNILVR, ALKEM and BHARTIARTL, each of which promptly lost")
    B("  about 15%. The depth is the market. The LAG is the strategy.")
    B()
    B("-" * 78)
    B("WHAT THIS SAYS ABOUT THE PRODUCTION BRAHMASTRA TRAIL: NOTHING")
    B("-" * 78)
    B("  RECORDED EXPLICITLY. The Module 4 result says NOTHING about the")
    B("  production Brahmastra trail on 15-minute futures. That code was")
    B("  NEITHER READ NOR TOUCHED. Module 4 tested a rescaled (10x/20x),")
    B("  daily-close-only reimplementation inside canslim_swing, against a")
    B("  different instrument class, a different timeframe and a different")
    B("  holding period. The original exits INTRABAR; this one cannot. A")
    B("  negative result here is not evidence against the original.")
    B()
    B("-" * 78)
    B("CLAUDE'S PRE-REGISTERED PREDICTIONS — BOTH FALSIFIED")
    B("-" * 78)
    B("  1. EXIT DOMINANCE — FALSIFIED.")
    B("     Predicted before Module 2: the EMA220 leg would almost never fire")
    B("     first, because entries sit a median 22% above the EMA220.")
    B("     Actual: the EMA220 leg was the DOMINANT exit, 82.4% of all exits in")
    B("     config A. Over a ~133-session hold the EMA rises to meet the price.")
    B()
    B("  2. FAST-EXIT DRAWDOWN BENEFIT — FALSIFIED.")
    B("     Predicted before Module 3: N=20 would cut max drawdown")
    B("     substantially, possibly under the 15% gate.")
    B("     Actual: it cut drawdown by 1.2 points (-25.36% -> -24.15%), nowhere")
    B("     near the gate. The same prediction's second half — that expectancy")
    B("     would be destroyed — HELD emphatically (+0.981R -> +0.062R).")
    B()
    B("-" * 78)
    B("REOPENING CONDITION")
    B("-" * 78)
    B("  This window is BURNT for this spec. NO FURTHER HISTORICAL RUN.")
    B("  Reopening requires FORWARD PAPER MODE ONLY. Any survivor from these")
    B("  modules is a hypothesis to be tested forward, never a validated")
    B("  configuration.")
    B()
    B("-" * 78)
    B("RETAINED ASSETS — the durable output of this project")
    B("-" * 78)
    B("  1. data/panel_v2/ — 188 symbols + NIFTY, 2015-01-01 to 2026-08-14,")
    B("     2,879-session calendar, SINGLE SOURCE (Dhan daily endpoint),")
    B("     corp-action adjusted and audited. Reusable by any future study.")
    B("  2. scripts/module1b_dedup.py — the general stacked-series resolver.")
    B("     Detects two price vintages returned in one response and picks the")
    B("     adjusted one by continuity, order-independently. Not symbol-specific.")
    B("  3. scripts/module2_backtest.py, module3_exitladder.py,")
    B("     module4_brahmastra.py — portfolio engines with the M5 cost model,")
    B("     matched-hold random-entry null, and gear-trail support.")
    B("  4. scripts/club1pct_benchmarks.py — benchmark harness (NIFTY, universe")
    B("     EW buy-and-hold, universe EW rebalanced), with mid-window listing")
    B("     handling stated.")
    B("  5. THE REGIME THERMOMETER — CORRECTED. A random entry in this universe,")
    B("     held for the strategy's own median 133 sessions (about six months),")
    B("     earned +1.2648 R MEAN and +0.9739 R MEDIAN per trade over 2015-2026,")
    B("     net of the full cost model and 0.05%/side slippage. On the registered")
    B("     R basis (0.15 x notional) that is about +19.0% mean / +14.6% median")
    B("     NET PER TRADE for buying at random and waiting six months.")
    B("     THE EARLIER FIGURE OF +0.44 R WAS WRONG — it came from the broken")
    B("     null and understated the regime by roughly 0.8 R.")
    B("     The thermometer is hold-dependent; at shorter holds it collapses:")
    B("       14-session hold  -> +0.0834 R    35-session hold -> +0.2352 R")
    B("       85-session hold  -> +0.6895 R   133-session hold -> +1.2648 R")
    B("     Any future strategy on this universe must be measured against the")
    B("     figure for ITS OWN holding period, not against a single number.")
    B("  6. scripts/club1pct_audit.py — the 360-degree correctness audit, and")
    B("     scripts/club1pct_null_fix.py — the corrected null. Both reusable.")
    B()
    B("  Caveat carried forward: the 188-symbol universe is TODAY'S F&O list")
    B("  frozen in 2026, so every result above — strategy and benchmark alike —")
    B("  carries selection bias and is an upper bound.")
    B()
    RP.write_text("\n".join(P) + "\n")
    print(f"written: {RP}  ({len(P)} lines)")


if __name__ == "__main__":
    main()
