#!/usr/bin/env python3
"""M6a report assembler — old-era data probe (go/no-go for Round-2)."""
from __future__ import annotations

from pathlib import Path

import pandas as pd

TRACK = Path(__file__).resolve().parents[1]
P = TRACK / "data" / "round2_probe"
REPORT = TRACK / "reports" / "swing_module6a_oldera_probe.txt"


def fmt(df):
    if df is None or len(df) == 0:
        return "  (none)\n"
    with pd.option_context("display.width", 200, "display.max_rows", len(df) + 5):
        return df.to_string(index=False) + "\n"


def main() -> None:
    usable = pd.read_parquet(P / "eps_usable.parquet")
    front = pd.read_parquet(P / "eps_frontier_dates.parquet")
    depth = pd.read_parquet(P / "eps_depth.parquet")
    yearly = pd.read_parquet(P / "eps_frontier.parquet")
    acts = pd.read_parquet(P / "oldera_corpactions.parquet")

    L, A = [], None
    A = L.append
    A("=" * 78)
    A("canslim-swing MODULE 6a — OLD-ERA DATA PROBE (Round-2 go/no-go)")
    A("Probe only. No full fetch. Cache: canslim_swing/data/round2_probe/")
    A("=" * 78)
    A("")
    A("HEADLINE: NO-GO for the Round-2 window as specified. Two independent")
    A("blockers, one of them structural and not fixable by retrying.")
    A("")
    A("-" * 78)
    A("1. DHAN DAILY PRICE DEPTH  ->  BLOCKED (credential, not capability)")
    A("")
    A("  Every request to POST /v2/charts/historical returned HTTP 401")
    A("  {errorType: Invalid_Authentication, errorCode: DH-901} for all 12 probe")
    A("  symbols AND the NIFTY index. The access token in pine_replica/.env has")
    A("  expired. Dhan tokens are short-lived and refreshing one requires an")
    A("  interactive login, which I will not perform on your behalf.")
    A("  => Daily depth back to 2014 is UNTESTED, not proven unavailable.")
    A("  => No failed response was cached, so a rerun after you refresh the token")
    A("     starts clean: `python3 canslim_swing/scripts/m6a_probe_prices.py`")
    A("")
    A("  FALLBACK ATTEMPTED: NSE's own historical price endpoints")
    A("  (/api/historical/cm/equity and /api/historical/securityArchives) both")
    A("  return HTTP 503 behind an HTML block page — NSE actively refuses them,")
    A("  unlike the corporate-filings endpoints used elsewhere in this track,")
    A("  which answered normally throughout this probe. So there is currently no")
    A("  working price path for the old era from either authorised source.")
    A("")
    A("  Note on the 5-year ceiling: the ~1,820-day cap in the habitat fetcher is")
    A("  an INTRADAY limit and says nothing about daily depth. Whether Dhan serves")
    A("  daily bars to 2014 remains the open question a token refresh would answer.")
    A("")
    A("-" * 78)
    A("2. OLD-ERA ADJUSTMENT SPOT-CHECK  ->  TARGETS IDENTIFIED, CHECK NOT RUN")
    A("")
    A("  Corp actions ARE retrievable from NSE (this half worked). Confirmed")
    A("  pre-2021 events to test a future price series against:")
    A(fmt(acts))
    A("  The check itself (M1-style: does the series cliff ~-50% at the ex-date?)")
    A("  needs the price history that step 1 could not fetch. This is the FIRST")
    A("  thing to run once a token exists, because Round-1 established that")
    A("  habitat's post-2021 data IS adjusted — that finding cannot be assumed to")
    A("  extend backwards through a different era of the vendor's history.")
    A("")
    A("-" * 78)
    A("3. NSE EPS OLD-REGIME DEPTH  ->  THE STRUCTURAL BLOCKER")
    A("")
    A("  The filing LIST goes back to 2005 for most symbols, so at first glance the")
    A("  window looks covered. It is not: the list is an index of filings, and for")
    A("  the old era the filing CONTENT is not retrievable.")
    A("")
    A("  Per-symbol quarters in 2014-Q3 -> 2021-Q2 that yield a USABLE EPS:")
    A(fmt(usable))
    A("  'unusable_no_xbrl_fallback' = the detail API returned an empty payload AND")
    A("  the list row's xbrl link is a STUB (it literally ends in '/-'). That")
    A("  combination is unrecoverable: it is precisely the rescue path that saved")
    A("  726 NBFC filings in Round-1 (M2b), and it does not exist for old filings.")
    A("")
    A("  Earliest quarter with an extractable EPS, per symbol:")
    A(fmt(front))
    A("  The frontier is not a date — it is the filing's `format` field. Once a")
    A("  symbol's filings flip from format='Old' to format='New', EPS extracts")
    A("  cleanly; before that it is empty for every non-bank tested. Banks are the")
    A("  exception: HDFCBANK and SBIN return re_basic_eps throughout, 28/28.")
    A("")
    A("  Year-by-year evidence for the format frontier:")
    A(fmt(yearly))
    A("")
    A("  Coverage by sector type in the Round-2 window:")
    A("    banks (HDFCBANK, SBIN)            100%   (28/28 each)")
    A("    non-financials (RELIANCE, TITAN,")
    A("      SUNPHARMA, TATASTEEL, BPCL,")
    A("      PERSISTENT)                   ~50-54%  (14-15 of 28)")
    A("    NBFC (BAJFINANCE)                  11%   (3/27)")
    A("    insurer (SBILIFE)                   0%   (no old-regime list rows at all,")
    A("                                             same as the M2a finding)")
    A("    2017 IPOs (CDSL 70%, DIXON 82%)   higher only because their history")
    A("                                      begins after the format transition")
    A("")
    A("-" * 78)
    A("4. OLD XBRL / TAG SANITY")
    A("")
    A("  No NEW tag variant appeared — and that is not reassuring, because for the")
    A("  old era there is usually nothing to tag-match against. Findings:")
    A("    * Bank filings in format='Old' populate `re_basic_eps` in the detail")
    A("      API (HDFCBANK Mar-2015 11.40, SBIN Mar-2015 5.01). M2b's chain works.")
    A("    * Non-bank filings in format='Old' return detail_kind='none' — an empty")
    A("      payload with no EPS fields at all, so no tag chain can help.")
    A("    * NBFC (BAJFINANCE) returns an empty payload in EVERY year sampled")
    A("      2014-2021; in Round-1 those were recovered from the list row's XBRL")
    A("      URL, but that URL is a stub for all pre-~2019 filings.")
    A("    * The insurer could not be probed at all (no list rows), so the")
    A("      LI-taxonomy question from M2b is simply untestable in this era.")
    A("")
    A("-" * 78)
    A("5. FULL-FETCH ESTIMATE (188 symbols) — for the scenario where a token exists")
    A("")
    A("  Prices  2015-01-01 -> 2021-07-31: 1 daily request per symbol (Dhan serves a")
    A("          date range in one call) = ~188 requests + 1 index, ~4 minutes at")
    A("          1 req/s. Small — the price side is cheap IF the token works.")
    A("  EPS     2014-Q3 -> 2021-Q2: 1 list call + ~28 detail calls per symbol")
    A("          = ~5,450 requests, ~95-110 minutes at 1 req/s including the")
    A("          throttle pauses Round-1 measured (NSE stalls near ~600 requests")
    A("          per session; budget for 3-5 forced cooldowns).")
    A("  Realistic total: ~2 hours of wall clock, fully resumable.")
    A("  BUT on this probe's measured hit-rate, roughly HALF those EPS requests")
    A("  would return an empty payload that no fallback can rescue.")
    A("")
    A("=" * 78)
    A("HONEST ASSESSMENT — can Round-2's window be built as specified?")
    A("=" * 78)
    A("")
    A("  No, not as specified. The price half is merely blocked on an expired Dhan")
    A("  token and would likely be fine after a refresh — that is an errand, not a")
    A("  finding. The EPS half is the real answer, and it is structural: NSE's")
    A("  filing list reaches back to 2005, but the filing CONTENT does not. For")
    A("  every non-bank symbol tested, quarterly EPS is simply absent before the")
    A("  filing format flips to 'New' (2016-2018 depending on the company), the")
    A("  detail API returns an empty payload, and the XBRL link that rescued 726")
    A("  NBFC filings in Round-1 is a stub for that era. Measured coverage over")
    A("  2014-Q3 -> 2021-Q2 is 100% for banks, ~50% for large non-financials, 11%")
    A("  for the NBFC, and 0% for the insurer. A C-gate needs a year-ago quarter")
    A("  for every scan day; at ~50% coverage it would fail closed on roughly half")
    A("  the universe for the first half of the window, which does not produce a")
    A("  weaker test of CANSLIM — it produces a different, bank-and-recent-IPO-")
    A("  weighted strategy wearing CANSLIM's name.")
    A("")
    A("  THE SINGLE BIGGEST DATA RISK is not the missing EPS — it is that the gap")
    A("  is SECTOR-CORRELATED and would be invisible in aggregate counts. Banks")
    A("  survive it perfectly, NBFCs and insurers are wiped out, non-financials")
    A("  lose their pre-2018 half. Any Round-2 built on this would silently become")
    A("  a study of financials and 2017-18 listings, and its C-gate would be")
    A("  strongest exactly where Round-1 already showed the data is most awkward.")
    A("  If Round-2 proceeds, the honest options are to start the window at the")
    A("  format frontier (roughly 2018, which shortens it to ~3.5 years and loses")
    A("  the 2016-17 regime the round was meant to test), or to source EPS from a")
    A("  vendor with genuine old-era fundamentals rather than from NSE's archive.")
    A("")
    A("=" * 78)
    REPORT.parent.mkdir(parents=True, exist_ok=True)
    REPORT.write_text("\n".join(L) + "\n")
    print(f"REPORT: {REPORT}")


if __name__ == "__main__":
    main()
