"""Public API for strategy versioning.

Thin orchestration layer that combines :mod:`store` (persistence) with
:mod:`diff` (comparison) to expose the six operations the rest of the
backend will call:

* :func:`create_version`
* :func:`get_version`
* :func:`list_versions`
* :func:`get_latest_version`
* :func:`compare_versions`
* :func:`rollback_to_version`

All callers go through this module — ``store`` is an implementation
detail and tests that touch the disk can do so via this surface plus
the test-only ``store.set_base_dir``. Phase 3 will swap ``store`` for
a DB-backed implementation; this module's signatures will not change.
"""

from __future__ import annotations

import copy
from datetime import UTC, datetime
from typing import Any
from uuid import UUID, uuid4

from app.strategy_engine.strategy_versioning import store
from app.strategy_engine.strategy_versioning.diff import (
    diff_strategy_json,
    summarise_hinglish,
)
from app.strategy_engine.strategy_versioning.models import (
    StrategyVersion,
    StrategyVersionComparison,
)


class StrategyVersionNotFoundError(LookupError):
    """Raised when the caller asks for a strategy id or version
    number that has no record in the store."""


def create_version(
    strategy_id: UUID,
    strategy_json: dict[str, Any],
    user_id: UUID,
    change_summary: str = "",
) -> StrategyVersion:
    """Append a new version to the strategy's history.

    Sequence numbers are assigned monotonically by the store —
    callers don't pick them. The first version of any strategy is
    ``version_number=1`` with ``parent_version_id=None``; every
    subsequent version links back to its predecessor.

    The ``strategy_json`` dict is deep-copied before being stored so
    later mutations of the caller's dict don't bleed into the
    persisted snapshot.
    """
    payload = copy.deepcopy(strategy_json)
    store._ensure_json_safe(payload)

    # Read the existing tail and write the new entry under a single
    # lock acquire so concurrent creators on the same strategy can't
    # both pick the same version_number.
    with store.lock():
        history = store.load_all_versions(strategy_id)
        parent = history[-1] if history else None
        version_number = store.next_version_number(strategy_id)
        version = StrategyVersion(
            version_id=uuid4(),
            strategy_id=strategy_id,
            version_number=version_number,
            strategy_json=payload,
            change_summary=change_summary,
            created_by=user_id,
            created_at=datetime.now(UTC),
            parent_version_id=parent.version_id if parent else None,
        )
        store.save_version(version)
    return version


def get_version(strategy_id: UUID, version_number: int) -> StrategyVersion:
    """Return the requested version or raise
    :class:`StrategyVersionNotFoundError`."""
    found = store.load_version(strategy_id, version_number)
    if found is None:
        raise StrategyVersionNotFoundError(
            f"strategy {strategy_id} has no version {version_number}"
        )
    return found


def list_versions(strategy_id: UUID) -> list[StrategyVersion]:
    """Return every version for a strategy in chronological order
    (oldest first). Empty list when the strategy has no history."""
    return store.load_all_versions(strategy_id)


def get_latest_version(strategy_id: UUID) -> StrategyVersion:
    """Return the highest-numbered version for ``strategy_id``.

    Raises:
        StrategyVersionNotFoundError: when the strategy has no
            versions yet.
    """
    history = store.load_all_versions(strategy_id)
    if not history:
        raise StrategyVersionNotFoundError(
            f"strategy {strategy_id} has no versions"
        )
    return history[-1]


def compare_versions(
    strategy_id: UUID,
    from_version: int,
    to_version: int,
) -> StrategyVersionComparison:
    """Return a structured diff between two versions of a strategy.

    ``from_version`` and ``to_version`` may be in any order — the
    diff is always interpreted as ``from → to``. The Hinglish summary
    is generated by :func:`diff.summarise_hinglish` from the diff
    list, so adding fields to the strategy schema doesn't require
    touching this function.
    """
    older = get_version(strategy_id, from_version)
    newer = get_version(strategy_id, to_version)
    diffs = diff_strategy_json(older.strategy_json, newer.strategy_json)
    summary = summarise_hinglish(older.strategy_json, newer.strategy_json, diffs)
    return StrategyVersionComparison(
        from_version=from_version,
        to_version=to_version,
        diffs=diffs,
        summary_hinglish=summary,
    )


def rollback_to_version(
    strategy_id: UUID,
    target_version: int,
    user_id: UUID,
) -> StrategyVersion:
    """Roll a strategy back to ``target_version`` by writing a *new*
    version whose payload matches the target's payload.

    History is **never** deleted — the rollback is itself a recorded
    edit, with a generated ``change_summary`` like
    ``"Rolled back to v3"``. This keeps the audit trail intact and
    lets a user roll forward again by rolling back to the version
    they came from.

    Raises:
        StrategyVersionNotFoundError: when ``target_version`` does
            not exist for the strategy.
    """
    target = get_version(strategy_id, target_version)
    return create_version(
        strategy_id=strategy_id,
        strategy_json=target.strategy_json,
        user_id=user_id,
        change_summary=f"Rolled back to v{target_version}",
    )


__all__ = [
    "StrategyVersionNotFoundError",
    "compare_versions",
    "create_version",
    "get_latest_version",
    "get_version",
    "list_versions",
    "rollback_to_version",
]
