#!/usr/bin/env python3
"""Generate API reference docs from the FastAPI OpenAPI schema.

Two execution modes:

1. **Import-app mode (preferred):** import the FastAPI app, build the
   OpenAPI schema in-process, write per-tag markdown files. Requires
   the full backend dep tree (bcrypt, asyncpg, etc).

2. **Live-server mode (fallback):** hit ``GET /openapi.json`` against
   a running backend instance.

Output: ``docs/api/INDEX.md`` + ``docs/api/<TAG>.md`` per router tag.

Usage::

    # Import-app mode (run from backend/ dir):
    cd backend && python ../scripts/generate_api_docs.py --import

    # Live-server mode (default):
    python scripts/generate_api_docs.py --url http://localhost:8000

Hard rules:
    * NO live API tokens or secrets written to output
    * Endpoint examples use placeholder values
    * Per-route descriptions are pulled from docstrings
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from collections import defaultdict
from pathlib import Path
from typing import Any


REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT_DIR = REPO_ROOT / "docs" / "api"


def fetch_openapi_via_import() -> dict[str, Any]:
    """Build the OpenAPI dict by importing the FastAPI app."""
    # Set safe env vars so config imports don't crash
    os.environ.setdefault("JWT_SECRET", "doc-gen-placeholder-do-not-use")
    os.environ.setdefault("ENCRYPTION_KEY", "JlPyLqr5K8XnZc9wK_OoUq8YyfZ2RhxbgkY7vxBfFu4=")
    os.environ.setdefault("ENVIRONMENT", "test")
    sys.path.insert(0, str(REPO_ROOT / "backend"))
    try:
        from app.main import create_app  # type: ignore[import-untyped]
    except Exception as exc:
        raise RuntimeError(
            f"Could not import app.main.create_app: {exc}. "
            f"Either install backend deps (pip install -e backend/) or "
            f"use --url to hit a live server instead."
        ) from exc
    app = create_app()
    return app.openapi()


def fetch_openapi_via_url(url: str) -> dict[str, Any]:
    """Hit /openapi.json on a running server."""
    try:
        import urllib.request

        with urllib.request.urlopen(f"{url.rstrip('/')}/openapi.json", timeout=10) as r:
            return json.loads(r.read())
    except Exception as exc:
        raise RuntimeError(f"Could not fetch {url}/openapi.json: {exc}") from exc


def render_route(path: str, method: str, op: dict[str, Any]) -> str:
    """Render one route as a markdown section."""
    summary = op.get("summary", "")
    desc = op.get("description", "").strip()
    parts = [f"### `{method.upper()} {path}`"]
    if summary:
        parts.append(f"\n**{summary}**\n")
    if desc:
        # Trim docstring to first paragraph for readability
        first_para = desc.split("\n\n")[0].replace("\n", " ").strip()
        parts.append(f"\n{first_para}\n")

    # Request body schema reference
    rb = op.get("requestBody", {})
    if rb:
        content = rb.get("content", {})
        for mime, body_spec in content.items():
            schema_ref = body_spec.get("schema", {}).get("$ref", "")
            schema_name = schema_ref.split("/")[-1] if schema_ref else ""
            if schema_name:
                parts.append(f"\n**Request body** (`{mime}`): `{schema_name}`")

    # Response codes
    responses = op.get("responses", {})
    if responses:
        parts.append("\n**Responses:**\n")
        for code in sorted(responses):
            r = responses[code]
            r_desc = r.get("description", "").split("\n")[0]
            parts.append(f"- `{code}` — {r_desc}")
    parts.append("\n")
    return "\n".join(parts)


def group_by_tag(openapi: dict[str, Any]) -> dict[str, list[tuple[str, str, dict]]]:
    """Group routes by their first tag. Routes without tags land in
    ``_untagged``."""
    by_tag: dict[str, list[tuple[str, str, dict]]] = defaultdict(list)
    for path, ops in openapi.get("paths", {}).items():
        for method, op in ops.items():
            if method not in ("get", "post", "put", "patch", "delete"):
                continue
            tags = op.get("tags", []) or ["_untagged"]
            tag = tags[0]
            by_tag[tag].append((path, method, op))
    return by_tag


def slug_for_tag(tag: str) -> str:
    """Tag → uppercase markdown filename (drop hyphens)."""
    return tag.upper().replace("-", "_").replace(" ", "_")


def write_per_tag(by_tag: dict[str, list[tuple[str, str, dict]]]) -> None:
    """Write one MD file per tag."""
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    for tag, routes in sorted(by_tag.items()):
        filename = OUTPUT_DIR / f"{slug_for_tag(tag)}.md"
        sections = [f"# {tag} — API reference\n"]
        sections.append(
            "*Auto-generated by `scripts/generate_api_docs.py`. Edit the "
            "source docstrings + regenerate.*\n"
        )
        for path, method, op in sorted(routes, key=lambda r: (r[0], r[1])):
            sections.append(render_route(path, method, op))
        filename.write_text("\n".join(sections))
        print(f"  wrote {filename.relative_to(REPO_ROOT)}")


def write_index(by_tag: dict[str, list[tuple[str, str, dict]]]) -> None:
    """Top-level INDEX.md with one-line summary per endpoint."""
    lines = [
        "# API Reference — INDEX",
        "",
        "*Auto-generated. See `docs/api/README.md` for regeneration.*",
        "",
        f"Total endpoints: {sum(len(v) for v in by_tag.values())}",
        "",
    ]
    for tag in sorted(by_tag):
        slug = slug_for_tag(tag)
        lines.append(f"## [{tag}]({slug}.md)")
        lines.append("")
        for path, method, op in sorted(by_tag[tag], key=lambda r: (r[0], r[1])):
            summary = op.get("summary", "").strip() or op.get("description", "").split("\n")[0].strip()
            summary = summary[:100]
            lines.append(f"- `{method.upper()} {path}` — {summary}")
        lines.append("")
    (OUTPUT_DIR / "INDEX.md").write_text("\n".join(lines))
    print(f"  wrote {(OUTPUT_DIR / 'INDEX.md').relative_to(REPO_ROOT)}")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--url",
        default=None,
        help="URL of running backend (e.g. http://localhost:8000)",
    )
    parser.add_argument(
        "--import",
        dest="import_mode",
        action="store_true",
        help="Build OpenAPI by importing the FastAPI app",
    )
    args = parser.parse_args()

    try:
        if args.import_mode:
            print("Building OpenAPI via app import…")
            openapi = fetch_openapi_via_import()
        elif args.url:
            print(f"Fetching OpenAPI from {args.url}…")
            openapi = fetch_openapi_via_url(args.url)
        else:
            # Try import first, fall back to URL if not provided
            print("Trying import mode (no --url given)…")
            try:
                openapi = fetch_openapi_via_import()
            except Exception as e:
                print(f"  import failed: {e}", file=sys.stderr)
                print("  pass --url <backend-url> to use live-server mode.", file=sys.stderr)
                return 2
    except RuntimeError as e:
        print(f"ERROR: {e}", file=sys.stderr)
        return 1

    by_tag = group_by_tag(openapi)
    print(f"Found {sum(len(v) for v in by_tag.values())} endpoints across {len(by_tag)} tags.")
    write_index(by_tag)
    write_per_tag(by_tag)
    print("Done.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
