"""Phase F reference tests — TRADETRI indicators vs Pine ground truth.

Independent ground-truth tests for the 5 MVP indicators. The expected
CSVs at :file:`fixtures/*_pine_expected.csv` are generated by
:file:`fixtures/_generate_phase_f_fixtures.py` using
``pandas-ta-classic`` (cross-verified against hand-rolled Pine
reference math from the Phase F deviation analysis — see
``PHASE_F_DEVIATION_ANALYSIS.md`` + ``PHASE_F_DEVIATION_ANALYSIS_PART2.md``
at repo root). The hand-roll matches TA-Lib's NaN convention exactly,
so the fixtures align positionally with TRADETRI's output.

Coverage gap these tests close
    The existing per-indicator tests at :file:`test_{sma,ema,rsi,macd,bb}.py`
    use fixture CSVs (``shared_input.csv`` + ``{name}_expected.csv``)
    that were generated FROM TA-Lib output — they're self-referential
    and cannot catch a TA-Lib regression or a wrong-direction
    post-processing correction (see Part 1 audit on BB band-width
    inflation). These reference tests use an INDEPENDENT source
    (pandas-ta-classic + hand-rolled Pine math) and break that
    tautology.

Tolerance
    ``rtol=1e-4, atol=1e-6`` — generous enough to absorb float
    accumulation differences between TA-Lib's C kernel and pandas-ta-
    classic's pandas/numpy path (the cross-verification in the
    fixture generator showed max diffs of 1e-8 to 1e-14 across all
    indicators). Tighter than 0.01% — well below any signal-relevant
    threshold.

How to regenerate the fixtures (manual, throwaway venv)::

    python3 -m venv /tmp/phase-f-venv
    /tmp/phase-f-venv/bin/pip install numpy pandas ta-lib==0.6.4 \\
        pydantic pandas-ta-classic
    cd backend
    PYTHONPATH=. /tmp/phase-f-venv/bin/python \\
        tests/services/indicators/fixtures/_generate_phase_f_fixtures.py
"""

from __future__ import annotations

import math
from pathlib import Path

import numpy as np
import pytest

from app.schemas.indicator import (
    BbParams,
    EmaParams,
    MacdParams,
    RsiParams,
    SmaParams,
)
from app.services.indicators.bb import BollingerBandsIndicator
from app.services.indicators.ema import EmaIndicator
from app.services.indicators.macd import MacdIndicator
from app.services.indicators.rsi import RsiIndicator
from app.services.indicators.sma import SmaIndicator
from tests.services.indicators.conftest import (
    load_expected_csv,
    load_input_csv,
)

_FIX_DIR = Path(__file__).parent / "fixtures"
_INPUT_CSV = _FIX_DIR / "nifty_100_bars_5m.csv"

# Tolerance choice — calibrated to catch real convention bugs, not
# float-accumulation noise. Cross-verification of pandas-ta-classic
# vs hand-rolled Pine reference (see fixture generator) showed natural
# noise of 1e-8 to 1e-14 across all 5 indicators. The known BB
# convention bug (``bb.py:67-72`` correction inflates bands by
# sqrt(20/19) ≈ 2.6% at length=20) produces ~2 absolute on NIFTY-
# priced bars (price ~22000, band offset ~85, correction adds ~2).
# atol=0.01 (one paisa on ₹22000) sits in the middle: 6 orders of
# magnitude above natural noise, 2 orders of magnitude below the BB
# bug signal — catches the bug, doesn't false-positive on epsilon.
_RTOL = 1e-7
_ATOL = 1e-2


def _assert_series_matches_pine(
    series_name: str,
    got: np.ndarray,
    expected: list[float | None],
) -> None:
    """Compare a TRADETRI ndarray against a Pine-reference list.

    Both must have the same length. ``None`` in ``expected`` means
    NaN — the corresponding ``got`` value must also be NaN. For
    non-None expected values, compare to ``got`` under
    ``np.testing.assert_allclose(rtol, atol)``.

    Surfaces a clear per-bar error message on mismatch so triage
    doesn't require re-running with extra prints.
    """
    assert len(got) == len(expected), (
        f"{series_name}: length {len(got)} != expected {len(expected)}"
    )
    for i, (g, e) in enumerate(zip(got.tolist(), expected)):
        if e is None:
            assert math.isnan(g), (
                f"{series_name}[{i}]: expected NaN, got {g}"
            )
        else:
            assert not math.isnan(g), (
                f"{series_name}[{i}]: expected {e}, got NaN"
            )
            # Use np.allclose semantics: |g - e| <= atol + rtol * |e|
            tol = _ATOL + _RTOL * abs(e)
            assert abs(g - e) <= tol, (
                f"{series_name}[{i}]: expected {e:.10f}, got {g:.10f}, "
                f"diff {abs(g - e):.3e}, tol {tol:.3e}"
            )


# ═══════════════════════════════════════════════════════════════════════
# Per-indicator reference tests
# ═══════════════════════════════════════════════════════════════════════


def test_sma_matches_pine_reference() -> None:
    """SMA(20) on 100-bar synthetic series must match Pine reference."""
    candles = load_input_csv(_INPUT_CSV)
    expected = load_expected_csv(_FIX_DIR / "sma_20_pine_expected.csv")
    got = SmaIndicator().compute(candles, SmaParams(length=20))["value"]
    _assert_series_matches_pine("sma_value", got, expected["value"])


def test_ema_matches_pine_reference() -> None:
    """EMA(20) on 100-bar synthetic series must match Pine reference.

    Phase F deviation analysis (Part 1) confirmed TA-Lib EMA and Pine
    EMA agree to float64 epsilon post-warmup; this test pins that
    against an INDEPENDENT pandas-ta-classic-derived reference.
    """
    candles = load_input_csv(_INPUT_CSV)
    expected = load_expected_csv(_FIX_DIR / "ema_20_pine_expected.csv")
    got = EmaIndicator().compute(candles, EmaParams(length=20))["value"]
    _assert_series_matches_pine("ema_value", got, expected["value"])


def test_rsi_matches_pine_reference() -> None:
    """RSI(14) on 100-bar synthetic series must match Pine reference."""
    candles = load_input_csv(_INPUT_CSV)
    expected = load_expected_csv(_FIX_DIR / "rsi_14_pine_expected.csv")
    got = RsiIndicator().compute(candles, RsiParams(length=14))["value"]
    _assert_series_matches_pine("rsi_value", got, expected["value"])


def test_macd_matches_pine_reference() -> None:
    """MACD(12,26,9) — pins TRADETRI's chosen TA-Lib aligned-seeding output.

    Queue UU (2026-05-31) resolved the deferred xfail: ``macd.py``
    ships ``talib.MACD`` directly (ALIGNED seeding — fast EMA seeded
    at index ``slow-1`` with the immediately-preceding ``fast``
    closes). This is the industry default; pandas-ta-classic's
    ``ta.macd()`` and every TA-Lib downstream consumer produce the
    same series. The Pine-docs INDEPENDENT-seeding convention
    (each EMA seeded at its own ``length-1``) diverges by up to ~1
    absolute on the first ~10 bars after slow-EMA warmup and decays
    to machine noise; empirically on RC1 720-bar synthetic + the
    Phase F 100-bar NIFTY fixture the divergence produces zero
    sign flips, zero crossover-timing changes, and identical
    trade counts on both live MACD templates. The fixture
    ``macd_12_26_9_pine_expected.csv`` is therefore the ALIGNED
    output; this test pins the convention TRADETRI shipped.

    Full investigation + customer-impact quantification:
    ``docs/QUEUE_UU_MACD_INVESTIGATION.md`` +
    ``docs/QUEUE_UU_MACD_RESOLUTION.md``.
    """
    candles = load_input_csv(_INPUT_CSV)
    expected = load_expected_csv(_FIX_DIR / "macd_12_26_9_pine_expected.csv")
    out = MacdIndicator().compute(
        candles,
        MacdParams(fast_length=12, slow_length=26, signal_length=9),
    )
    _assert_series_matches_pine("macd",      out["macd"],      expected["macd"])
    _assert_series_matches_pine("signal",    out["signal"],    expected["signal"])
    _assert_series_matches_pine("histogram", out["histogram"], expected["histogram"])


def test_bollinger_matches_pine_reference() -> None:
    """Bollinger(20, 2) — all three series must match Pine reference.

    Phase F deviation analysis (Part 1) found this test would FAIL
    pre-fix because ``bb.py:67-72`` applies a ``sqrt(N/(N-1))``
    correction that inflates the bands ~2.6% wider than Pine. After
    the bug fix (remove the correction), this test passes.
    """
    candles = load_input_csv(_INPUT_CSV)
    expected = load_expected_csv(
        _FIX_DIR / "bollinger_20_2_pine_expected.csv"
    )
    out = BollingerBandsIndicator().compute(
        candles, BbParams(length=20, stddev_multiplier=2.0)
    )
    _assert_series_matches_pine("upper",  out["upper"],  expected["upper"])
    _assert_series_matches_pine("middle", out["middle"], expected["middle"])
    _assert_series_matches_pine("lower",  out["lower"],  expected["lower"])


# ═══════════════════════════════════════════════════════════════════════
# Adapter equivalence — backtest_adapter must agree with underlying classes
# ═══════════════════════════════════════════════════════════════════════


def test_backtest_adapter_matches_classes() -> None:
    """The ``backtest_adapter`` free functions must produce output
    identical to the underlying class-based API.

    Pure composition — the adapter just wraps the existing classes.
    Float-identity expected.
    """
    from app.services.indicators import backtest_adapter as ba

    candles = load_input_csv(_INPUT_CSV)
    close = np.array([float(c.close) for c in candles], dtype=np.float64)

    np.testing.assert_array_equal(
        ba.sma(close, period=20),
        SmaIndicator().compute(candles, SmaParams(length=20))["value"],
        err_msg="sma adapter diverges from SmaIndicator",
    )
    np.testing.assert_array_equal(
        ba.ema(close, period=20),
        EmaIndicator().compute(candles, EmaParams(length=20))["value"],
        err_msg="ema adapter diverges from EmaIndicator",
    )
    np.testing.assert_array_equal(
        ba.rsi(close, period=14),
        RsiIndicator().compute(candles, RsiParams(length=14))["value"],
        err_msg="rsi adapter diverges from RsiIndicator",
    )

    macd_class = MacdIndicator().compute(
        candles, MacdParams(fast_length=12, slow_length=26, signal_length=9)
    )
    macd_adapter = ba.macd(close)
    np.testing.assert_array_equal(macd_adapter.macd, macd_class["macd"])
    np.testing.assert_array_equal(macd_adapter.signal, macd_class["signal"])
    np.testing.assert_array_equal(macd_adapter.histogram, macd_class["histogram"])

    bb_class = BollingerBandsIndicator().compute(
        candles, BbParams(length=20, stddev_multiplier=2.0)
    )
    bb_adapter = ba.bollinger(close)
    np.testing.assert_array_equal(bb_adapter.upper, bb_class["upper"])
    np.testing.assert_array_equal(bb_adapter.middle, bb_class["middle"])
    np.testing.assert_array_equal(bb_adapter.lower, bb_class["lower"])


# ═══════════════════════════════════════════════════════════════════════
# Adapter validation surface — quick sanity, full coverage in unit tests
# ═══════════════════════════════════════════════════════════════════════


def test_adapter_rejects_2d_input() -> None:
    from app.services.indicators import backtest_adapter as ba

    with pytest.raises(ValueError, match="1-D"):
        ba.sma(np.array([[1.0, 2.0], [3.0, 4.0]]), period=2)


def test_adapter_rejects_inf() -> None:
    from app.services.indicators import backtest_adapter as ba

    arr = np.array([1.0, 2.0, np.inf, 4.0, 5.0, 6.0])
    with pytest.raises(ValueError, match="inf"):
        ba.sma(arr, period=3)


def test_adapter_rejects_too_short_input() -> None:
    from app.services.indicators import backtest_adapter as ba

    with pytest.raises(ValueError, match="needs at least"):
        ba.sma(np.array([1.0, 2.0, 3.0]), period=20)
