/**
 * The founder's FOUR picker cards (26 Sep 2026, REQUIREMENTS §13 — the vehicle order):
 * FUTURES · CASH · OPTION BUY · SPREADS, in his build order. SPREADS is ONE card that
 * carries its two directions (bull call on a long signal, bear put on a short) — the
 * backend's five vehicles and their sealed bars are unchanged.
 *
 * Every locked card says exactly what it is waiting for and quotes its OWN sealed bar
 * (kb/customer/VEHICLE_BARS.md v2). Paper counts are the COUNTED ones (inside the
 * bar's window); a count this page cannot know renders the literal NOT MEASURED.
 *
 * SOURCE, one per fact:
 *   - "live"   → the backend's flag-gated `/customer-lane/vehicles/board` (the gate
 *                computed fresh from flags + the bars file + the paper records).
 *   - "static" → `vehicle-board.static.json`, GENERATED by the backend's own
 *                `vehicles.board()` (backend/scripts/dump_vehicle_board_static.py) —
 *                the same sentences, never retyped here. It exists so the four cards
 *                can be shown on the site BEFORE the backend surface is deployed; it
 *                carries no count it cannot know (paper counts are NOT MEASURED).
 *   Selected by `NEXT_PUBLIC_VEHICLE_PICKER_SOURCE` ("static" | anything else = live).
 *   The readiness interlock (itmgr/20260926-guided-path-fe) may pass `source` instead.
 */

import { NOT_MEASURED } from "@/lib/risk-labels";
import type { CustomerVehicle, VehicleBoard, VehicleStatus } from "@/lib/customer-vehicles";
import staticBoard from "@/lib/vehicle-board.static.json";

export const PICKER_SOURCE_FLAG = "NEXT_PUBLIC_VEHICLE_PICKER_SOURCE";
export type PickerSource = "live" | "static";

/** "static" only when the env says exactly that. Read at call time so tests can flip it.
 * Literal spelling on purpose — the only form Next's docs promise to inline (see
 * customerVehiclesEnabled). */
export function vehiclePickerSource(): PickerSource {
  return process.env.NEXT_PUBLIC_VEHICLE_PICKER_SOURCE === "static" ? "static" : "live";
}

/** Founder, 26 Sep: "FUTURES … Lot sizes 2/4/6/8/10 and long/short/both". */
export const FUTURES_LOT_CHOICES = [2, 4, 6, 8, 10] as const;
export const DIRECTION_CHOICES = [
  { value: "long", label: "Sirf long" },
  { value: "short", label: "Sirf short" },
  { value: "both", label: "Dono" },
] as const;

export type CardId = "FUTURES" | "CASH" | "OPTION_BUY" | "SPREADS";

export const PICKER_CARDS: ReadonlyArray<{ card: CardId; label: string; members: readonly CustomerVehicle[] }> = [
  { card: "FUTURES", label: "Futures", members: ["FUTURES"] },
  { card: "CASH", label: "Cash (shares)", members: ["CASH"] },
  { card: "OPTION_BUY", label: "Option buy", members: ["OPTION_BUY"] },
  { card: "SPREADS", label: "Spreads", members: ["BULL_CALL_SPREAD", "BEAR_PUT_SPREAD"] },
];

export interface PickerCard {
  card: CardId;
  label: string;
  open: boolean;
  selectable: boolean;
  members: VehicleStatus[];
}

/** Group the visible vehicles into the four cards, in the founder's order. A card with
 * no visible member is not shown (with every flag OFF live, that is FUTURES alone). */
export function groupIntoCards(vehicles: VehicleStatus[]): PickerCard[] {
  const by = new Map(vehicles.filter((v) => v.visible).map((v) => [v.vehicle, v] as const));
  const out: PickerCard[] = [];
  for (const c of PICKER_CARDS) {
    const members = c.members.map((m) => by.get(m)).filter((v): v is VehicleStatus => Boolean(v));
    if (members.length)
      out.push({
        card: c.card,
        label: c.label,
        open: members.some((m) => m.open),
        selectable: members.some((m) => Boolean(m.selectable)),
        members,
      });
  }
  return out;
}

/** The generated static board: all four cards visible, nothing open, counts NOT MEASURED. */
export function staticVehicleBoard(): VehicleBoard {
  return staticBoard as unknown as VehicleBoard;
}

/** "N of 30 closed paper trades (counted)" — or NOT MEASURED, never a guess. */
export function paperProgress(v: VehicleStatus): string {
  const n = v.paper_trades_so_far;
  const need = v.min_paper_trades;
  if (typeof n !== "number") return `Paper trades gine gaye: ${NOT_MEASURED}`;
  const needText = typeof need === "number" ? ` / ${need}` : "";
  const pre = typeof v.paper_trades_pre_window === "number" && v.paper_trades_pre_window > 0
    ? ` (window se pehle ke ${v.paper_trades_pre_window} nahi gine jaate)`
    : "";
  return `Paper trades gine gaye: ${n}${needText}${pre}`;
}

/** The sealed bar as short lines, in the bar's own order; nothing restated. */
export function barLines(v: VehicleStatus): string[] {
  const b = v.bar ?? {};
  const pick: Array<[string, string]> = [
    ["B1_net_after_billed_charges_and_spread", "Net (Dhan ke billed charges ke baad)"],
    ["B1b_net_over_worst_drawdown", "Net ÷ worst drawdown"],
    ["B2_worst_drawdown_rupees", "Worst drawdown"],
    ["B2b_worst_single_trade_rupees", "Worst single trade"],
    ["B3_spread_paid", "Spread jo chukaaya"],
    ["B4_minimum_capital_measured", "Minimum capital (measured)"],
    ["B5_margin", "Margin"],
  ];
  const lines = pick.filter(([k]) => typeof b[k] === "string" && b[k]).map(([k, label]) => `${label}: ${b[k]}`);
  if (typeof v.min_paper_trades === "number" && typeof v.min_trading_days === "number") {
    lines.unshift(`Kam se kam ${v.min_paper_trades} band paper trades aur ${v.min_trading_days} trading din`);
  }
  return lines;
}
